//go:build !ignore_autogenerated

package v1alpha1

import runtime "k8s.io/apimachinery/pkg/runtime"

func (in *AutoInstrumentation) DeepCopyInto(out *AutoInstrumentation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

func (in *AutoInstrumentation) DeepCopy() *AutoInstrumentation {
	if in == nil {
		return nil
	}
	out := new(AutoInstrumentation)
	in.DeepCopyInto(out)
	return out
}

func (in *AutoInstrumentation) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *AutoInstrumentationList) DeepCopyInto(out *AutoInstrumentationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AutoInstrumentation, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *AutoInstrumentationList) DeepCopy() *AutoInstrumentationList {
	if in == nil {
		return nil
	}
	out := new(AutoInstrumentationList)
	in.DeepCopyInto(out)
	return out
}

func (in *AutoInstrumentationList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}
