package v1alpha1

// Code generated by scripts/generate-plugin-fields.sh. DO NOT EDIT.
//
// This file contains instrumentation plugin fields for InstrumentationSpec.
// These fields are generated from the plugin registry in
// operator/internal/controller/plugins/registry.go
//
// To regenerate after adding/removing plugins:
//   scripts/generate-plugin-fields.sh

// InstrumentationPluginFields contains fields for all registered instrumentation plugins.
// This type is embedded into InstrumentationSpec.
type InstrumentationPluginFields struct {
	// FastAPI enables fastapi instrumentation.
	// Can be:
	// - true: Platform instruments (explicit)
	// - false: App instruments (explicit)
	// - "auto": Runtime ownership resolution (auto-detection)
	// - omitted: Defaults to EnableInstrumentation value
	FastAPI interface{} `json:"fastapi,omitempty"`

	// HTTPX enables httpx instrumentation.
	// Can be:
	// - true: Platform instruments (explicit)
	// - false: App instruments (explicit)
	// - "auto": Runtime ownership resolution (auto-detection)
	// - omitted: Defaults to EnableInstrumentation value
	HTTPX interface{} `json:"httpx,omitempty"`

	// Requests enables requests instrumentation.
	// Can be:
	// - true: Platform instruments (explicit)
	// - false: App instruments (explicit)
	// - "auto": Runtime ownership resolution (auto-detection)
	// - omitted: Defaults to EnableInstrumentation value
	Requests interface{} `json:"requests,omitempty"`

	// LangChain enables langchain instrumentation.
	// Can be:
	// - true: Platform instruments (explicit)
	// - false: App instruments (explicit)
	// - "auto": NOT SUPPORTED - validation will reject this value
	// - omitted: Defaults to EnableInstrumentation value
	LangChain interface{} `json:"langchain,omitempty"`

	// MCP enables mcp instrumentation.
	// Can be:
	// - true: Platform instruments (explicit)
	// - false: App instruments (explicit)
	// - "auto": NOT SUPPORTED - validation will reject this value
	// - omitted: Defaults to EnableInstrumentation value
	MCP interface{} `json:"mcp,omitempty"`

	// Openai enables openai instrumentation.
	// Can be:
	// - true: Platform instruments (explicit)
	// - false: App instruments (explicit)
	// - "auto": Runtime ownership resolution (auto-detection)
	// - omitted: Defaults to EnableInstrumentation value
	Openai interface{} `json:"openai,omitempty"`

}
