//go:build !ignore_autogenerated

package v1alpha1

import runtime "k8s.io/apimachinery/pkg/runtime"

func (in *AgentObservabilityDemo) DeepCopyInto(out *AgentObservabilityDemo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

func (in *AgentObservabilityDemo) DeepCopy() *AgentObservabilityDemo {
	if in == nil {
		return nil
	}
	out := new(AgentObservabilityDemo)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentObservabilityDemo) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *AgentObservabilityDemoList) DeepCopyInto(out *AgentObservabilityDemoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AgentObservabilityDemo, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *AgentObservabilityDemoList) DeepCopy() *AgentObservabilityDemoList {
	if in == nil {
		return nil
	}
	out := new(AgentObservabilityDemoList)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentObservabilityDemoList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}
