#!/usr/bin/env bash
#
# Generate plugin fields for CRD and Go types from plugin registry.
#
# This script reads the plugin registry (operator/internal/controller/plugins/registry.go)
# and generates:
# 1. operator/api/v1alpha1/agentobservability_types_generated.go - Go struct fields
# 2. manifests/crd/agentobservability-crd.yaml - CRD schema fields (between markers)
#
# Usage:
#   scripts/generate-plugin-fields.sh
#
# The script must be run from the repository root.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

cd "${REPO_ROOT}"

echo "Generating plugin fields from registry..."

# Extract plugin names from registry.go
# Looking for lines like: &FastAPIPlugin{},
PLUGIN_NAMES=($(grep -E '^\s*&[A-Z][a-zA-Z]+Plugin\{\},' operator/internal/controller/plugins/registry.go | \
    sed -E 's/.*&([A-Z][a-zA-Z]+)Plugin\{\}.*/\1/' | \
    tr '[:upper:]' '[:lower:]'))

if [ ${#PLUGIN_NAMES[@]} -eq 0 ]; then
    echo "Error: No plugins found in registry.go"
    exit 1
fi

echo "Found ${#PLUGIN_NAMES[@]} plugins: ${PLUGIN_NAMES[*]}"

# ============ Generate Go struct fields ============

GO_OUTPUT="operator/api/v1alpha1/agentobservability_types_generated.go"

echo "Generating Go types: ${GO_OUTPUT}"

cat > "${GO_OUTPUT}" << 'EOF'
package v1alpha1

// Code generated by scripts/generate-plugin-fields.sh. DO NOT EDIT.
//
// This file contains instrumentation plugin fields for InstrumentationSpec.
// These fields are generated from the plugin registry in
// operator/internal/controller/plugins/registry.go
//
// To regenerate after adding/removing plugins:
//   scripts/generate-plugin-fields.sh

// InstrumentationPluginFields contains fields for all registered instrumentation plugins.
// This type is embedded into InstrumentationSpec.
type InstrumentationPluginFields struct {
EOF

# Generate field for each plugin
for plugin in "${PLUGIN_NAMES[@]}"; do
    # Capitalize first letter for field name
    FIELD_NAME="$(echo "${plugin:0:1}" | tr '[:lower:]' '[:upper:]')${plugin:1}"

    # Special cases for specific plugins
    case "${plugin}" in
        "fastapi")
            FIELD_NAME="FastAPI"
            ;;
        "httpx")
            FIELD_NAME="HTTPX"
            ;;
        "langchain")
            FIELD_NAME="LangChain"
            ;;
        "mcp")
            FIELD_NAME="MCP"
            ;;
    esac

    # Determine if plugin supports auto-detection (for comment)
    AUTO_SUPPORTED="true"
    if [ "${plugin}" = "langchain" ] || [ "${plugin}" = "mcp" ]; then
        AUTO_SUPPORTED="false"
    fi

    # Generate field with appropriate comment
    cat >> "${GO_OUTPUT}" << EOF
	// ${FIELD_NAME} enables ${plugin} instrumentation.
	// Can be:
	// - true: Platform instruments (explicit)
	// - false: App instruments (explicit)
EOF

    if [ "${AUTO_SUPPORTED}" = "true" ]; then
        cat >> "${GO_OUTPUT}" << EOF
	// - "auto": Runtime ownership resolution (auto-detection)
EOF
    else
        cat >> "${GO_OUTPUT}" << EOF
	// - "auto": NOT SUPPORTED - validation will reject this value
EOF
    fi

    cat >> "${GO_OUTPUT}" << EOF
	// - omitted: Defaults to EnableInstrumentation value
	${FIELD_NAME} interface{} \`json:"${plugin},omitempty"\`

EOF
done

cat >> "${GO_OUTPUT}" << 'EOF'
}
EOF

echo "Generated ${GO_OUTPUT}"

# ============ Generate CRD YAML fields ============

CRD_YAML="manifests/crd/agentobservability-crd.yaml"

echo "Generating CRD fields: ${CRD_YAML}"

# Check if markers exist
if ! grep -q "# GENERATED_PLUGIN_FIELDS_START" "${CRD_YAML}"; then
    echo "Error: CRD YAML missing # GENERATED_PLUGIN_FIELDS_START marker"
    exit 1
fi

if ! grep -q "# GENERATED_PLUGIN_FIELDS_END" "${CRD_YAML}"; then
    echo "Error: CRD YAML missing # GENERATED_PLUGIN_FIELDS_END marker"
    exit 1
fi

# Generate new plugin fields section
PLUGIN_FIELDS_YAML=$(mktemp)

cat > "${PLUGIN_FIELDS_YAML}" << 'EOF'
                    # GENERATED_PLUGIN_FIELDS_START
                    # Plugin fields generated by scripts/generate-plugin-fields.sh
                    # DO NOT EDIT THIS SECTION MANUALLY
EOF

for plugin in "${PLUGIN_NAMES[@]}"; do
    # Determine if plugin supports auto-detection
    AUTO_SUPPORTED="true"
    if [ "${plugin}" = "langchain" ] || [ "${plugin}" = "mcp" ]; then
        AUTO_SUPPORTED="false"
    fi

    cat >> "${PLUGIN_FIELDS_YAML}" << EOF
                    ${plugin}:
                      description: |-
                        Enable ${plugin} instrumentation. Can be:
                        - true: Platform instruments (explicit)
                        - false: App instruments (explicit)
EOF

    if [ "${AUTO_SUPPORTED}" = "true" ]; then
        cat >> "${PLUGIN_FIELDS_YAML}" << EOF
                        - "auto": Runtime ownership resolution (auto-detection)
                        - omitted: Defaults to true when enableInstrumentation is true
EOF
    else
        cat >> "${PLUGIN_FIELDS_YAML}" << EOF
                        - "auto": NOT SUPPORTED - validation will reject this value
                        - omitted: Defaults to true when enableInstrumentation is true
                        Note: "auto" is not supported for ${plugin}
EOF
    fi

    cat >> "${PLUGIN_FIELDS_YAML}" << EOF
                      x-kubernetes-preserve-unknown-fields: true
                      nullable: true
EOF
done

cat >> "${PLUGIN_FIELDS_YAML}" << 'EOF'
                    # GENERATED_PLUGIN_FIELDS_END
EOF

# Replace section between markers in CRD YAML
awk '
    /# GENERATED_PLUGIN_FIELDS_START/ {
        while (getline < "'"${PLUGIN_FIELDS_YAML}"'") print
        # Skip until end marker
        while (getline && !/# GENERATED_PLUGIN_FIELDS_END/) {}
        next
    }
    { print }
' "${CRD_YAML}" > "${CRD_YAML}.tmp"

mv "${CRD_YAML}.tmp" "${CRD_YAML}"
rm "${PLUGIN_FIELDS_YAML}"

echo "Updated ${CRD_YAML}"

echo "Plugin field generation complete!"
echo ""
echo "Generated files:"
echo "  - ${GO_OUTPUT}"
echo "  - ${CRD_YAML} (updated between markers)"
echo ""
echo "Next steps:"
echo "  1. Review generated files"
echo "  2. Run 'go test ./operator/internal/controller/...'"
echo "  3. Commit changes if tests pass"
