#!/usr/bin/env python3
"""
Generate requirements.txt for custom Python auto-instrumentation image.

This script reads the plugin registry and collects all plugin dependencies,
combining them with base OTel packages to generate core/custom-python-image/requirements.txt.

Usage:
    python core/scripts/generate-requirements.py

The script can be run from anywhere, but is typically run from the repository root.
"""

import sys
from pathlib import Path

# Resolve paths relative to this script's location
SCRIPT_DIR = Path(__file__).parent
CORE_ROOT = SCRIPT_DIR.parent
REPO_ROOT = CORE_ROOT.parent
RUNTIME_COORDINATOR = CORE_ROOT / "runtime-coordinator"

# Add runtime-coordinator to path to import plugins
sys.path.insert(0, str(RUNTIME_COORDINATOR))

# Base OpenTelemetry packages required by all instrumentation
BASE_PACKAGES = [
    "opentelemetry-api>=1.30,<2.0",
    "opentelemetry-sdk>=1.30,<2.0",
    "opentelemetry-exporter-otlp>=1.30,<2.0",
    "PyYAML>=6.0,<7.0",
]


def main():
    print("Generating requirements.txt from plugin dependencies...")

    # Import plugin registry
    try:
        from agent_obs_runtime.plugins.registry import INSTRUMENTATION_PLUGINS
    except ImportError as e:
        print(f"Error: Failed to import plugin registry: {e}", file=sys.stderr)
        print("Make sure you're running from the repository root", file=sys.stderr)
        sys.exit(1)

    # Collect all plugin dependencies
    all_dependencies = set(BASE_PACKAGES)
    plugin_count = 0

    for plugin in INSTRUMENTATION_PLUGINS:
        plugin_name = plugin.name
        try:
            deps = plugin.dependencies()
            if deps:
                print(f"  {plugin_name}: {len(deps)} package(s)")
                all_dependencies.update(deps)
            else:
                print(f"  {plugin_name}: no external dependencies")
            plugin_count += 1
        except Exception as e:
            print(f"Warning: Failed to get dependencies for {plugin_name}: {e}", file=sys.stderr)

    print(f"\nProcessed {plugin_count} plugins")
    print(f"Total unique packages: {len(all_dependencies)}")

    # Sort dependencies for consistent output
    sorted_deps = sorted(all_dependencies)

    # Write to requirements.txt
    output_path = CORE_ROOT / "custom-python-image" / "requirements.txt"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with output_path.open("w") as f:
        f.write("# Generated by core/scripts/generate-requirements.py\n")
        f.write("# DO NOT EDIT MANUALLY - this file is generated from plugin dependencies\n")
        f.write("#\n")
        f.write("# To regenerate after modifying plugin dependencies:\n")
        f.write("#   python core/scripts/generate-requirements.py\n")
        f.write("\n")
        for dep in sorted_deps:
            f.write(f"{dep}\n")

    print(f"\nGenerated {output_path}")
    print("\nNext steps:")
    print("  1. Review generated requirements.txt")
    print("  2. Rebuild custom Python image: make build-core-images")
    print("  3. Test with demo apps")


if __name__ == "__main__":
    main()
